version: 0.2

env:
  variables:
    FLUTTER_HOME: /opt/flutter
    AWS_ACCOUNT_ID: "535615247325"
    IMAGE_REPO_NAME: "vittaglico-frontend"
    IMAGE_TAG: "latest"
    AWS_REGION: "us-east-2"

phases:
  install:
    commands:
      - git clone https://github.com/flutter/flutter.git $FLUTTER_HOME
      - export PATH="$PATH:$FLUTTER_HOME/bin"
      - flutter channel stable
      - flutter upgrade
      - flutter doctor -v
      - flutter pub get
  build:
    commands:
      - flutter build web --release
      - echo "Construindo imagem Docker com Nginx para Flutter Web..."
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG -f Dockerfile .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG 535615247325.dkr.ecr.us-east-2.amazonaws.com/vittaglico-frontend:$IMAGE_TAG
  post_build:
    commands:
      - echo "Autenticando com o ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - echo "Enviando imagem para o ECR..."
      - docker push 535615247325.dkr.ecr.us-east-2.amazonaws.com/vittaglico-frontend:$IMAGE_TAG
      - echo "Imagem enviada para o ECR: 535615247325.dkr.ecr.us-east-2.amazonaws.com/vittaglico-frontend:$IMAGE_TAG"

artifacts:
  files:
    - '**/*'
  base-directory: 'build/web'