version: 0.2

env:
  variables:
    FLUTTER_HOME: /opt/flutter

phases:
  install:
    commands:
      - git clone https://github.com/flutter/flutter.git $FLUTTER_HOME
      - export PATH="$PATH:$FLUTTER_HOME/bin"
      - flutter channel stable
      - flutter upgrade
      - flutter doctor -v
      - flutter pub get
  build:
    commands:
      - flutter build web --release
  post_build:
    commands:
      - aws s3 sync build/web s3://$AWS_S3_BUCKET --delete

artifacts:
  files:
    - '**/*'
  base-directory: 'build/web'